# Generated by Django 5.0.3 on 2024-03-31 03:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkedUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file_uuid', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='csv_files/')),
                ('file_name', models.CharField(max_length=255)),
                ('chunk_qtd', models.IntegerField()),
                ('chunk_idx', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chunked_upload',
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('governmentId', models.CharField()),
                ('debtAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debtDueDate', models.CharField()),
                ('debtId', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'debt',
            },
        ),
    ]
