# Generated by Django 5.0.3 on 2024-03-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
