# Generated by Django 5.0.3 on 2024-03-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handling', '0002_debt_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='debt',
            name='debtAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='debt',
            name='debtDueDate',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debt',
            name='debtId',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debt',
            name='governmentId',
            field=models.CharField(blank=True, null=True),
        ),
    ]
